### ISSUE TITLE
HTML anatomy of items in the layers list needs refactoring

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/Web-Map-Custom-Element#263]
## HTML anatomy of a layer item

```html
<fieldset aria-grabbed="false">
    <details class="mapml-control-layers">
        <summary>
            <label>
                <input checked="" type="checkbox" class="leaflet-control-layers-selector" />
                <span style="font-style: normal;"> Canada Base Map - Transportation (CBMT)</span>
            </label>
        </summary>
        <details class="mapml-control-layers">
            <summary>
                <label for="o82">Opacity</label>
            </summary>
            <input id="o82" type="range" min="0" max="1.0" value="1.0" step="0.1" />
        </details>
    </details>
</fieldset>
```

### Nesting interactive elements inside `<summary>` is problematic:

- `<summary>` is not keyboard operable if it has descendant `<label>`/`<input>` _when using a screen reader_. This is a critical issue. I filed NVDA bug: https://github.com/nvaccess/nvda/issues/12008.
- Nesting interactive elements is generally [adviced against](https://github.com/w3c/aria/issues/1285).
- Interactive content in `<summary>` specifically may be disallowed in the future: https://github.com/whatwg/html/issues/2272.
- `<summary>` isn't clickable using a mouse pointer due to nested `<label>`, this required disabling `pointer-events` of `<label>` (using a perhaps not so robust selector) in [mapml.css#L321](https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/15e8157501d47dadc5b473ed8171879b366252ae/src/mapml.css#L321).

Refactoring the layer items is not a small task (it may inadvertently fix #90). First we need to decide on a new layout that does not entail nesting interactive elements in `<summary>`, sigh.

**Comment by Malvoz** [comment]
Legend links are also problematic since they're interactive elements, inside summary.

**Comment by Malvoz** [comment]
We should also ensure that the `<fieldset>` elements are properly labelled, which can be accomplished using [`<legend>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/legend). However there are limitations with `<legend>` (and `<fieldset>`):

  1. Required to be the first child of `fieldset` (so imposes a certain visual design)
  2. May be problematic if wanting/needing to use CSS flexbox/grid specifically, since the rendering/layout model was only recently revamped (which allows for these `display` styles) https://github.com/whatwg/html/pull/3934.

Instead of `<fieldset>` we can use `<div role="region">` (which is the implicit `role` for the element), and label the element using `aria-label`/`aria-labelledby` (allows the layer name to be placed elsewhere in the DOM structure, so does not impose a certain visual design).

**Comment by Malvoz** [comment]
## Proposal for alternative layer item anatomy:

```html
<fieldset class="mapml-layer-item" aria-labelledby="mapml-layer-item-name-{1}" aria-grabbed="false">
  <div class="mapml-layer-item-properties">
    <label class="mapml-layer-item-toggle" title="Enable layer">
      <input type="checkbox" checked />
    </label>

    <span class="mapml-layer-item-name" id="mapml-layer-item-name-{1}">Layer 1</span>

    <div class="mapml-layer-item-controls">
      <button type="button" class="mapml-layer-item-remove-control mapml-button" title="Remove layer">
        <span class="mapml-button-icon" aria-hidden="true">
          <!-- icon (inline SVG or CSS background-image) -->
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" height="22" width="22">
            <path d="M0 0h24v24H0V0z" fill="none" />
            <path d="M18.3 5.71c-.39-.39-1.02-.39-1.41 0L12 10.59 7.11 5.7c-.39-.39-1.02-.39-1.41 0-.39.39-.39 1.02 0 1.41L10.59 12 5.7 16.89c-.39.39-.39 1.02 0 1.41.39.39 1.02.39 1.41 0L12 13.41l4.89 4.89c.39.39 1.02.39 1.41 0 .39-.39.39-1.02 0-1.41L13.41 12l4.89-4.89c.38-.38.38-1.02 0-1.4z"/>
          </svg>
        </span>
      </button>

      <button type="button" class="mapml-layer-item-settings-control mapml-button" title="Layer settings" aria-expanded="false">
        <span class="mapml-button-icon" aria-hidden="true">
          <!-- icon (inline SVG or CSS background-image) -->
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" height="22" width="22">
            <path d="M0 0h24v24H0z" fill="none" />
            <path d="M12 8c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zm0 2c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm0 6c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2z" />
          </svg>
        </span>
      </button>
    </div>
  </div>

  <div class="mapml-layer-item-settings" hidden>
    <details class="mapml-layer-item-opacity">
      <summary id="mapml-layer-item-opacity-name-{1}">Opacity</summary>
      <input type="range" min="0" max="1.0" value="1.0" step="0.1" aria-labelledby="mapml-layer-item-opacity-name-{1}" />
    </details>
  </div>
</fieldset>
```

The proposed anatomy:
- _does use_ `<fieldset>` (to allow `disable` of an entire layer list item, but it's not used as a flex container since that has interop issues)
- ensures that each [fieldset is properly labelled for ATs using ARIA](https://www.w3.org/WAI/tutorials/forms/grouping/#associating-related-controls-with-wai-aria)
- describes the [purpose](https://www.w3.org/TR/WCAG21/#identify-purpose) of each control for ATs
- does not use nested interactive elements
- does not use any pre-existing class names (although these may be improved)
- uses [icons](https://material.io/resources/icons/) available under Apache license v2.0

<details>
<summary><strong>Required CSS</strong></summary><br>

(side note: these required styles also introduce a generic `mapml-button` class to reset native styles of buttons, it could be re-used in the future when/if implementing actual buttons as opposed to `<a>` controls, which are problematic for numerous reasons, listed in https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/247.) 

```css
.mapml-button {
  background-color: transparent;
  border: none;
  border-radius: 0;
  color: inherit;
  font: inherit;
  line-height: inherit;
  margin: 0;
  padding: 0;
  overflow: visible;
  text-transform: none;
  -webkit-appearance: none;
     -moz-appearance: none;
          appearance: none;
}

button.mapml-button:disabled,
button.mapml-button[aria-disabled="true"],
.mapml-layer-item:disabled button.mapml-button {
  opacity: .3;
}

.mapml-button-icon {
  pointer-events: none;
}

.mapml-button-icon svg {
  fill: currentColor;
}

.mapml-layer-item,
.mapml-layer-item *,
.mapml-layer-item ::before,
.mapml-layer-item ::after {
  box-sizing: border-box;
}

.mapml-layer-item {
  border: 0;
  margin: 0;
  padding: 0;
}

.mapml-layer-item:not(:last-of-type) {
  border-bottom: 1px solid #e3e3e3;
}

.mapml-layer-item-properties {
  align-items: center;
  display: flex;
  justify-content: space-between;
}

.mapml-layer-item-controls {
  margin-inline-start: auto;
}

.mapml-layer-item-controls button svg {
  vertical-align: middle;
}

.mapml-layer-item-controls,
label.mapml-layer-item-toggle,
.mapml-layer-item-remove-control {
  align-items: center;
  display: flex;
  justify-content: center;
}

.mapml-layer-item-name {
  padding: .5rem;
  padding-inline-start: 0;
  word-break: break-word;
}

.mapml-layer-item-toggle,
.mapml-layer-item-remove-control,
.mapml-layer-item-settings-control {
  min-height: 44px;
  min-width: 44px;
  height: 44px;
  width: 44px;
}

.mapml-layer-item-settings > * {
  display: block;
  padding-block-start: .25rem;
  padding-block-end: .25rem;
  padding-inline-start: 44px;
  padding-inline-end: 20px;
}

.mapml-layer-item-settings summary {
  -webkit-user-select: none;
          user-select: none;
}

.mapml-layer-item-opacity [type="range"] {
  margin-inline-end: 0;
  margin-inline-start: 0;
  width: 100%;
}
```

</details>

The required styles:
- ensure that each control is 44 by 44 px (https://github.com/Maps4HTML/Web-Map-Custom-Element/issues/215)
- uses [Logical Properties](https://www.w3.org/TR/css-logical/) such that alignment and spacing makes sense if the author embeds the map in `<html dir="rtl">`.

### Implementation details:

- `<fieldset>` should be labelled by the layer name
- `<button class="mapml-layer-item-settings-control">` should default to `aria-expanded="false"`
- `<div class="mapml-layer-item-settings">` should  default to `hidden`
- When the `<button class="mapml-layer-item-settings-control">` is pressed:
  - Its `aria-expanded` attribute is set to `true`
  - the corresponding `<div class="mapml-layer-item-settings">`'s `hidden` attribute is removed.
- In `<details class="mapml-layer-item-opacity">` the `<input type="range">` should be labelled by `<summary>`

<hr>

#### Result:

<details>
<summary>(from copy & pasting 2 example layer items into the existing layer control along with the required CSS)</summary><br>

```html
<!-- Example disabled layer item -->
<fieldset class="mapml-layer-item" aria-labelledby="mapml-layer-item-name-{1}" aria-grabbed="false" disabled>
  <div class="mapml-layer-item-properties">
    <label class="mapml-layer-item-toggle" title="Enable layer">
      <input type="checkbox" checked />
    </label>

    <span class="mapml-layer-item-name" id="mapml-layer-item-name-{1}">Layer 1</span>

    <div class="mapml-layer-item-controls">
      <button type="button" class="mapml-layer-item-remove-control mapml-button" title="Remove layer">
        <span class="mapml-button-icon" aria-hidden="true">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" height="22" width="22">
            <path d="M0 0h24v24H0V0z" fill="none" />
            <path d="M18.3 5.71c-.39-.39-1.02-.39-1.41 0L12 10.59 7.11 5.7c-.39-.39-1.02-.39-1.41 0-.39.39-.39 1.02 0 1.41L10.59 12 5.7 16.89c-.39.39-.39 1.02 0 1.41.39.39 1.02.39 1.41 0L12 13.41l4.89 4.89c.39.39 1.02.39 1.41 0 .39-.39.39-1.02 0-1.41L13.41 12l4.89-4.89c.38-.38.38-1.02 0-1.4z"/>
          </svg>
        </span>
      </button>

      <button type="button" class="mapml-layer-item-settings-control mapml-button" title="Layer settings" aria-expanded="false">
        <span class="mapml-button-icon" aria-hidden="true">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" height="22" width="22">
            <path d="M0 0h24v24H0z" fill="none" />
            <path d="M12 8c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zm0 2c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm0 6c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2z" />
          </svg>
        </span>
      </button>
    </div>
  </div>

  <div class="mapml-layer-item-settings" hidden>
    <details class="mapml-layer-item-opacity">
      <summary id="mapml-layer-item-opacity-name-{1}">Opacity</summary>
      <input type="range" min="0" max="1.0" value="1.0" step="0.1" aria-labelledby="mapml-layer-item-opacity-name-{1}" />
    </details>
  </div>
</fieldset>

<!-- Example enabled layer item with expanded settings -->
<fieldset class="mapml-layer-item" aria-labelledby="mapml-layer-item-name-{2}" aria-grabbed="false">
  <div class="mapml-layer-item-properties">
    <label class="mapml-layer-item-toggle" title="Enable layer">
      <input type="checkbox" checked />
    </label>

    <span class="mapml-layer-item-name" id="mapml-layer-item-name-{2}">Layer 2, this has a longer name</span>

    <div class="mapml-layer-item-controls">
      <button type="button" class="mapml-layer-item-remove-control mapml-button" title="Remove layer">
        <span class="mapml-button-icon" aria-hidden="true">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" height="22" width="22">
            <path d="M0 0h24v24H0V0z" fill="none" />
            <path d="M18.3 5.71c-.39-.39-1.02-.39-1.41 0L12 10.59 7.11 5.7c-.39-.39-1.02-.39-1.41 0-.39.39-.39 1.02 0 1.41L10.59 12 5.7 16.89c-.39.39-.39 1.02 0 1.41.39.39 1.02.39 1.41 0L12 13.41l4.89 4.89c.39.39 1.02.39 1.41 0 .39-.39.39-1.02 0-1.41L13.41 12l4.89-4.89c.38-.38.38-1.02 0-1.4z"/>
          </svg>
        </span>
      </button>

      <button type="button" class="mapml-layer-item-settings-control mapml-button" title="Layer settings" aria-expanded="true">
        <span class="mapml-button-icon" aria-hidden="true">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" height="22" width="22">
            <path d="M0 0h24v24H0z" fill="none" />
            <path d="M12 8c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zm0 2c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm0 6c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2z" />
          </svg>
        </span>
      </button>
    </div>
  </div>

  <div class="mapml-layer-item-settings">
    <details class="mapml-layer-item-opacity">
      <summary id="mapml-layer-item-opacity-name-{2}">Opacity</summary>
      <input type="range" min="0" max="1.0" value="1.0" step="0.1" aria-labelledby="mapml-layer-item-opacity-name-{2}" />
    </details>
  </div>
</fieldset>
```

</details>

![alt-layer-list-item-anatomy](https://user-images.githubusercontent.com/26493779/112196050-ea18fd80-8c0a-11eb-8ed7-183c28488e9d.png)

Thoughts?
