### ISSUE TITLE
Controls not displaying properly when printing

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/Web-Map-Custom-Element#294]
Trying to print a page with a map you'll find that controls that use background images as icons don't display:

<img width="600" src="https://user-images.githubusercontent.com/26493779/107879248-0b821d80-6ed8-11eb-9a12-95066ef42cd6.png" alt>

Background images are usually not included for printing because they can generally use up a lot of color.

Workarounds include:

- Hide controls (except attribution perhaps) when printing:<br><br>
  ```css
  @media print {
   .leaflet-control:not(.leaflet-control-attribution) {
      display: none;
    }
  }
  ```
  This may not be optimal because there may be cases where users want to print to show a UI setting for example. And if they want to print without the UI they can toggle controls off in the context menu.<br><br>
- Force printers to include the controls:<br><br>
  ```css
  @media print {
    .leaflet-control {
      -webkit-print-color-adjust: exact; /* https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-print-color-adjust */
                    color-adjust: exact; /* https://developer.mozilla.org/en-US/docs/Web/CSS/color-adjust */
    }
  }
  ```
- Don't use background-image for buttons

<hr>

As a side note I should probably raise an issue with Leaflet and the Fullscreen plugin, in case they too would be interested in fixing this.
